fun parseBoolean(string:String) = java.lang.Boolean.valueOf(string)
fun parseByte(string:String) = java.lang.Byte.valueOf(string)
fun parseShort(string:String) = java.lang.Short.valueOf(string)
fun parseInt(string:String) = java.lang.Integer.valueOf(string)
fun parseLong(string:String) = java.lang.Long.valueOf(string)
fun parseFloat(string:String) = java.lang.Float.valueOf(string)
fun parseDouble(string:String) = java.lang.Double.valueOf(string)
